server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

short-link:
  domain:
    default: localhost:8001
  stats:
    locale:
      amap-key: your-amap-key-here
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - lu.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
